CMDSCRIPT /usr/local/bin/nut-test-logic.sh
PIPEFN /run/nut/upssched/upssched.pipe
LOCKFN /run/nut/upssched/upssched.lock

AT ONBATT * START-TIMER power-down 5
AT ONLINE * CANCEL-TIMER power-down power-up
