# Copyright (c) 2026 T3CHNRD. All rights reserved.
# ------------------------------------------------------------------
# GENERATED TEMPLATE: /etc/nut/upsd.conf
# ------------------------------------------------------------------
LISTEN 127.0.0.1 3493
