user = root
group = nut

[ups1]
    driver = snmp-ups
    port = 192.168.3.153
    community = [REDACTED]
    pollinterval = 2
    snmp_version = v1
    desc = "APC Smart-UPS 1500 (UPS_Test at DC/NS)"

[ups2]
    driver = usbhid-ups
    port = auto
    vendorid = 051d
    serial = 3B1237X19716
    desc = "APC Back-UPS RS 1500G"

[ups3]
    driver = usbhid-ups
    port = auto
    vendorid = 051d
    serial = JB0527045561
    desc = "APC Back-UPS XS 1200"

[ups4]
    driver = snmp-ups
    port = 192.168.3.152
    community = [REDACTED]
    snmp_version = v1
    desc = "APC Smart-UPS 3000"

[ups5]
    driver = snmp-ups
    port = 192.168.3.150
    community = [REDACTED]
    snmp_version = v1
    desc = "APC Smart-UPS 3000 XLM"

[ups6]
    driver = snmp-ups
    port = 192.168.3.154
    community = [REDACTED]
    snmp_version = v2c
    desc = "Tripp Lite SU3000RTXL3U"

[ups7]
    driver = snmp-ups
    port = 192.168.3.151
    community = [REDACTED]
    snmp_version = v2c
    desc = "Tripp Lite SU3000RTXL3U"

[ups8]
    driver = usbhid-ups
    port = auto
    vendorid = 051d
    serial = 4B1206P36742
    desc = "APC Back-UPS RS 1300G"

[ups9]
    driver = snmp-ups
    port = 192.168.3.252
    community = [REDACTED]
    snmp_version = v2c
    desc = "Tripp Lite SU5000RT4UHV"
