Alias /nut-ui/static/ /opt/nut-orchestrator-ui/static/

<Directory /opt/nut-orchestrator-ui/static/>
    Require all granted
</Directory>

<Location /nut-ui>
    AuthType Basic
    AuthName "NUT Orchestrator UI"
    AuthUserFile /etc/apache2/.htpasswd
    Require valid-user

    ProxyPass http://127.0.0.1:[REDACTED]
    ProxyPassReverse http://127.0.0.1:[REDACTED]
</Location>
